### ISSUE TITLE
This is a possible duplicate - fields with relations show ID instead of value from foreign table

### ISSUE THREAD

**Issue by Lovor01** [jan-vandenberg/cruddiy#31] opened 2021-06-07 08:56 UTC
Hello,
when I set up everything, fields with relations (foreign key) show their ID values instead of lookup values from referenced table. It would be very useful to enhance app with this basic functionality.

**Comment by jan-vandenberg** [comment] 2021-06-07 09:03
Duplicate of https://github.com/jan-vandenberg/cruddiy/issues/14

**Closed by jan-vandenberg** 2021-06-07 09:03 UTC
