### ISSUE TITLE
Warning upon wizard completion

### ISSUE THREAD

**Issue by Lovor01** [jan-vandenberg/cruddiy#32] opened 2021-06-07 08:58 UTC
On last screen of app generating wizard, I get:

 `Warning: count(): Parameter must be an array or an object that implements Countable in C:\Wamp.NET\sites\grocery\public\core\generate.php on line 3`

**Comment by jan-vandenberg** [comment] 2021-06-07 09:02
Interesting, I notice you're using a Windows environment? What PHP version are you using?

**Comment by Lovor01** [comment] 2021-06-07 09:13
php 7.4.15 (x64) on Apache via FastCGI

**Comment by jan-vandenberg** [comment] 2021-06-07 09:31
I use 7.4.18 so that can't be the problem I think. 

To debug/test you can delete the top piece of code in generate.php (delete line 3 through 11) or replace it for this version: https://raw.githubusercontent.com/jan-vandenberg/cruddiy/f8655699b9e42ff5d093b92cc80570300fd5be38/core/generate.php

**Comment by Lovor01** [comment] 2021-06-07 10:08
Thanks, I may look into it later, but it is not a critical issue (I thought it might be connected to ID's showing instead of related values from referenced tables, but this is not the case, as you reported it is not yet done).

**Comment by jan-vandenberg** [comment] 2022-03-30 15:43
I will close this issue for now, since there are no updates and I can't reproduce.

**Closed by jan-vandenberg** 2022-03-30 15:43 UTC
